name: Pull request

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Typescript
        run: yarn run tsc
